name: HH Build

on:
  workflow_dispatch:
    inputs:
      patch_name:
        description: 'Имя game_patch'
        required: true
        default: 'game_patch_4.6.0.21565'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install repak
        run: |
          curl -L https://github.com/trumank/repak/releases/download/v0.2.2/repak_cli-x86_64-unknown-linux-gnu.tar.xz -o repak.tar.xz
          tar -xJf repak.tar.xz
          sudo mv repak /usr/local/bin/
          repak --version

      - name: Keygen
        run: python3 build/keygen.py

      - name: Encrypt
        run: python3 build/encrypt.py

      - name: Pack PAK
        run: python3 build/pack.py
        env:
          PATCH_NAME: ${{ github.event.inputs.patch_name }}

      - name: Upload PAK
        uses: actions/upload-artifact@v4
        with:
          name: hh-patch
          path: out/*.pak
          if-no-files-found: error
